"""
Data models for test cases, results, and related structures.

All data classes use Pydantic for validation and serialization.
"""

from __future__ import annotations

import re
from typing import Any

from pydantic import BaseModel, Field, field_validator


class VerifyItem(BaseModel):
    """
    One assertion inside verify list.

    Three forms (mutually exclusive):
    1. cmd + (expect_contains | expect_regex) - Run command and match output
    2. cmd + save_to - Run command and save file to evidence
    3. judge: ai_vision - Take screenshot for AI/human judgment
    """

    cmd: str | None = None
    expect_contains: list[str] = Field(default_factory=list)
    expect_regex: str | None = None
    save_to: str | None = None
    judge: str | None = None
    description: str = ""

    # Capture part of stdout for later ${name} interpolation
    capture: str | None = None
    capture_from: str = "last_line"  # last_line | first_line | all | regex:<expr>

    @field_validator("capture_from")
    @classmethod
    def validate_capture_from(cls, v: str) -> str:
        if v.startswith("regex:"):
            expr = v[len("regex:"):]
            try:
                re.compile(expr)
            except re.error as e:
                raise ValueError(f"Invalid capture_from regex: {e}")
        elif v not in ("last_line", "first_line", "all"):
            raise ValueError(
                f"capture_from must be last_line/first_line/all/regex:<expr>, got {v!r}"
            )
        return v


class RequireItem(BaseModel):
    """
    Machine-checkable precondition.

    Unlike preconditions (free text), failing requires marks case SKIPPED
    rather than ERROR (environment gap vs product regression).
    """

    cmd: str
    expect_contains: list[str] = Field(default_factory=list)
    expect_regex: str | None = None
    description: str = ""


class KnownLimit(BaseModel):
    """
    Documented limitation that downgrades FAIL/ERROR to EXPECTED.

    pattern must match failure text to trigger downgrade.
    Bare reason without pattern is documentation only.
    """

    pattern: str | None = None
    reason: str = ""

    def matches(self, haystack: str) -> bool:
        if not self.pattern:
            return False
        return bool(re.search(self.pattern, haystack, re.IGNORECASE | re.MULTILINE))

    def describe(self) -> str:
        return self.reason or (self.pattern or "")

    @field_validator("pattern")
    @classmethod
    def validate_pattern(cls, v: str | None) -> str | None:
        if v is not None:
            try:
                re.compile(v)
            except re.error as e:
                raise ValueError(f"Invalid known_limits pattern regex: {e}")
        return v


class TestCase(BaseModel):
    """
    One test case loaded from YAML.

    New in v3.0:
    - test_data: dict injected into Agent goal context
    - steps: list of natural language steps (compiled to single goal)
    """

    id: str
    title: str
    priority: str = "smoke"  # smoke | full
    preconditions: list[str] = Field(default_factory=list)
    requires: list[RequireItem] = Field(default_factory=list)
    setup: str = ""

    # Task definition (choose one or both)
    task: str | None = None  # Legacy: single string
    steps: list[str] = Field(default_factory=list)  # New: step list
    test_data: dict[str, Any] = Field(default_factory=dict)  # New: context vars

    run_flags: dict[str, Any] = Field(default_factory=dict)
    verify: list[VerifyItem] = Field(default_factory=list)
    timeout: int = 600
    repeat: int = 1
    pass_criteria: str = ""
    cleanup: str = ""
    known_limits: KnownLimit | None = None

    # Metadata
    source_file: str = ""

    @field_validator("repeat")
    @classmethod
    def validate_repeat(cls, v: int) -> int:
        if v < 1:
            raise ValueError(f"repeat must be >= 1, got {v}")
        return v

    model_config = {"extra": "forbid"}


class CaseResult(BaseModel):
    """
    Outcome of executing one test case.

    Status values:
    - PASS: All verify checks passed
    - FAIL: One or more verify checks failed
    - ERROR: Environment issue (setup failed, screenshot capture failed)
    - PENDING_AI: Contains AI vision items awaiting judgment
    - EXPECTED: FAIL/ERROR but matched known_limits
    - SKIPPED: Not executed (requires not met)

    New in v3.0:
    - agent_steps: Actual steps MobileAgent executed
    - trajectory_path: Path to saved trajectory
    - compiled_goal: Goal string generated by compiler
    """

    case: TestCase
    status: str = "SKIPPED"
    detail: str = ""
    run_exit_code: int | None = None
    run_seconds: float = 0.0
    run_timed_out: bool = False
    verify_results: list[dict[str, Any]] = Field(default_factory=list)
    ai_judge_images: list[str] = Field(default_factory=list)

    # repeat > 1 data
    attempts: list[dict[str, Any]] = Field(default_factory=list)

    # v3.0 additions
    agent_steps: int = 0
    trajectory_path: str | None = None
    compiled_goal: str = ""

    def pass_rate(self) -> str:
        """Return 'n/N' over attempts, or empty string for single run."""
        if len(self.attempts) <= 1:
            return ""
        good = sum(1 for a in self.attempts if a.get("status") in ("PASS", "EXPECTED"))
        return f"{good}/{len(self.attempts)}"

    model_config = {"arbitrary_types_allowed": True}


# Status constants
PASS = "PASS"
FAIL = "FAIL"
ERROR = "ERROR"
PENDING_AI = "PENDING_AI"
EXPECTED = "EXPECTED"
SKIPPED = "SKIPPED"

FAILING = {FAIL, ERROR}
